import type { CoachingPhrase, PhraseType } from "@/types/trainer";

export const PHRASE_TYPE_CONFIG: Record<PhraseType, { icon: string; label: string; cls: string }> = {
  question:   { icon: "❓", label: "Question",   cls: "bg-blue-500/20 border-blue-400/30 text-blue-300" },
  statement:  { icon: "💬", label: "Statement",  cls: "bg-emerald-500/20 border-emerald-400/30 text-emerald-300" },
  transition: { icon: "🔄", label: "Transition", cls: "bg-purple-500/20 border-purple-400/30 text-purple-300" },
  challenge:  { icon: "⚡", label: "Challenge",  cls: "bg-orange-500/20 border-orange-400/30 text-orange-300" },
};

export const SEED_PHRASES: CoachingPhrase[] = [
  {
    phrase: "What's your plan here?",
    thai_meaning: "แผนของคุณในจุดนี้คืออะไร?",
    phrase_type: "question",
    phrase_pronunciation: "วอทส์ ยัวร์ แพลน เฮียร์?",
    word_breakdown: [
      { word: "What's", thai: "อะไรคือ",          pronunciation: "วอทส์" },
      { word: "your",   thai: "ของคุณ",            pronunciation: "ยัวร์" },
      { word: "plan",   thai: "แผน",               pronunciation: "แพลน" },
      { word: "here",   thai: "ในจุดนี้",           pronunciation: "เฮียร์" },
    ],
    keywords: ["plan", "here"],
    situation: "โค้ชถามก่อนที่ผู้เล่นจะตัดสินใจ เพื่อให้คิดถึง intention ก่อนกดปุ่ม",
    similar_phrases: ["What are you thinking here?", "What's the idea behind this play?"],
    match_term: "What's your plan?",
    match_thai: "แผนของคุณคืออะไร?",
  },
  {
    phrase: "Walk me through your thought process.",
    thai_meaning: "อธิบายกระบวนการคิดของคุณให้ฟังหน่อย",
    phrase_type: "statement",
    phrase_pronunciation: "วอค มี ทรู ยัวร์ ธอท โพรเซส",
    word_breakdown: [
      { word: "Walk",    thai: "พา/นำ",             pronunciation: "วอค" },
      { word: "me",      thai: "ฉัน",               pronunciation: "มี" },
      { word: "through", thai: "ผ่าน/ตลอด",         pronunciation: "ทรู" },
      { word: "your",    thai: "ของคุณ",            pronunciation: "ยัวร์" },
      { word: "thought", thai: "ความคิด",           pronunciation: "ธอท" },
      { word: "process", thai: "กระบวนการ",         pronunciation: "โพรเซส" },
    ],
    keywords: ["walk through", "thought process"],
    situation: "โค้ชขอให้ผู้เล่นอธิบายทีละขั้นว่าคิดอะไรอยู่ก่อนตัดสินใจ",
    similar_phrases: ["Take me through the hand step by step.", "Explain your reasoning here."],
    match_term: "Walk me through...",
    match_thai: "อธิบายกระบวนการคิด",
  },
  {
    phrase: "What are you trying to accomplish here?",
    thai_meaning: "คุณพยายามจะทำอะไรให้สำเร็จในจุดนี้?",
    phrase_type: "question",
    phrase_pronunciation: "วอท อาร์ ยู ไทรอิง ทู แอคคอมพลิช เฮียร์?",
    word_breakdown: [
      { word: "What",       thai: "อะไร",             pronunciation: "วอท" },
      { word: "are",        thai: "(กริยาช่วย)",      pronunciation: "อาร์" },
      { word: "you",        thai: "คุณ",              pronunciation: "ยู" },
      { word: "trying",     thai: "พยายาม",           pronunciation: "ไทรอิง" },
      { word: "to",         thai: "ที่จะ",            pronunciation: "ทู" },
      { word: "accomplish", thai: "ทำให้สำเร็จ",      pronunciation: "แอคคอมพลิช" },
      { word: "here",       thai: "ในจุดนี้",          pronunciation: "เฮียร์" },
    ],
    keywords: ["trying", "accomplish"],
    situation: "โค้ชถามเพื่อให้ผู้เล่นระบุเป้าหมายของ action ว่า value, bluff หรือ protection",
    similar_phrases: ["What's your goal with this bet?", "What are you trying to do here?"],
    match_term: "trying to accomplish?",
    match_thai: "พยายามทำอะไรให้สำเร็จ?",
  },
  {
    phrase: "I would argue that...",
    thai_meaning: "ผมคิดว่า... (แบบมีเหตุผลสนับสนุน)",
    phrase_type: "transition",
    phrase_pronunciation: "ไอ วูด อาร์กิว แดท",
    word_breakdown: [
      { word: "I",      thai: "ผม",                 pronunciation: "ไอ" },
      { word: "would",  thai: "จะ/อยาก",            pronunciation: "วูด" },
      { word: "argue",  thai: "โต้แย้ง/เสนอว่า",    pronunciation: "อาร์กิว" },
      { word: "that",   thai: "ว่า",                pronunciation: "แดท" },
    ],
    keywords: ["argue"],
    situation: "โค้ชใช้เมื่อต้องการเสนอความเห็นที่อาจต่างจากผู้เล่น โดยไม่ได้บอกว่าผิดตรงๆ",
    similar_phrases: ["I would say that...", "My view is that...", "I'd suggest that..."],
    match_term: "I would argue that...",
    match_thai: "ผมเสนอว่า... (มีเหตุผล)",
  },
  {
    phrase: "The reason why I like this bet is...",
    thai_meaning: "เหตุผลที่ผมชอบ bet นี้คือ...",
    phrase_type: "statement",
    phrase_pronunciation: "เดอะ รีซัน วาย ไอ ไลค์ ดิส เบท อิส",
    word_breakdown: [
      { word: "The",    thai: "(article)",           pronunciation: "เดอะ" },
      { word: "reason", thai: "เหตุผล",             pronunciation: "รีซัน" },
      { word: "why",    thai: "ที่",                pronunciation: "วาย" },
      { word: "I",      thai: "ผม",                 pronunciation: "ไอ" },
      { word: "like",   thai: "ชอบ",               pronunciation: "ไลค์" },
      { word: "this",   thai: "นี้",               pronunciation: "ดิส" },
      { word: "bet",    thai: "การ bet",            pronunciation: "เบท" },
      { word: "is",     thai: "คือ",               pronunciation: "อิส" },
    ],
    keywords: ["reason", "like", "bet"],
    situation: "โค้ชอธิบายว่าทำไมถึงชอบ action นั้น โดยให้เหตุผลที่เป็นรูปธรรม",
    similar_phrases: ["The thing I like about this line is...", "What makes this bet good is..."],
    match_term: "reason I like this bet",
    match_thai: "เหตุผลที่ชอบ bet นี้",
  },
  {
    phrase: "Given that his range is capped...",
    thai_meaning: "เมื่อพิจารณาว่า range ของเขาถูก cap อยู่...",
    phrase_type: "transition",
    phrase_pronunciation: "กิฟเวน แดท ฮิส เรนจ์ อิส แคพท์",
    word_breakdown: [
      { word: "Given",  thai: "เมื่อพิจารณาว่า",    pronunciation: "กิฟเวน" },
      { word: "that",   thai: "ว่า",                pronunciation: "แดท" },
      { word: "his",    thai: "ของเขา",             pronunciation: "ฮิส" },
      { word: "range",  thai: "range (มือที่เป็นไปได้)", pronunciation: "เรนจ์" },
      { word: "is",     thai: "ถูก",               pronunciation: "อิส" },
      { word: "capped", thai: "จำกัด/cap ไว้",      pronunciation: "แคพท์" },
    ],
    keywords: ["given", "range", "capped"],
    situation: "โค้ชใช้นำเข้าสู่การวิเคราะห์ โดยตั้งสมมติฐานเกี่ยวกับ range ของคู่ต่อสู้ก่อน",
    similar_phrases: ["Considering his range is limited here...", "Since he can't have the nuts here..."],
    match_term: "Given that his range is...",
    match_thai: "เมื่อพิจารณา range ของเขา",
  },
  {
    phrase: "You're essentially saying that...",
    thai_meaning: "สิ่งที่คุณกำลังบอกอยู่จริงๆ คือ...",
    phrase_type: "statement",
    phrase_pronunciation: "ยัวร์ อิสเซ็นเชียลลี เซย์อิง แดท",
    word_breakdown: [
      { word: "You're",      thai: "คุณกำลัง",         pronunciation: "ยัวร์" },
      { word: "essentially", thai: "โดยพื้นฐานแล้ว",   pronunciation: "อิสเซ็นเชียลลี" },
      { word: "saying",      thai: "บอก/สื่อ",         pronunciation: "เซย์อิง" },
      { word: "that",        thai: "ว่า",              pronunciation: "แดท" },
    ],
    keywords: ["essentially", "saying"],
    situation: "โค้ชสรุปความหมายเบื้องหลังของ action ที่ผู้เล่นทำ เพื่อให้เห็นภาพชัดขึ้น",
    similar_phrases: ["What you're really doing is...", "In other words, you're saying..."],
    match_term: "You're essentially saying...",
    match_thai: "สิ่งที่คุณสื่อจริงๆ คือ",
  },
  {
    phrase: "Does that make sense to you?",
    thai_meaning: "เข้าใจไหม? / สมเหตุสมผลสำหรับคุณไหม?",
    phrase_type: "question",
    phrase_pronunciation: "ดัซ แดท เมค เซนส์ ทู ยู?",
    word_breakdown: [
      { word: "Does",  thai: "(กริยาช่วย)",         pronunciation: "ดัซ" },
      { word: "that",  thai: "นั่น",               pronunciation: "แดท" },
      { word: "make",  thai: "ทำให้",              pronunciation: "เมค" },
      { word: "sense", thai: "สมเหตุสมผล",         pronunciation: "เซนส์" },
      { word: "to",    thai: "สำหรับ",             pronunciation: "ทู" },
      { word: "you",   thai: "คุณ",               pronunciation: "ยู" },
    ],
    keywords: ["make sense"],
    situation: "โค้ชถามหลังจากอธิบายจบ เพื่อเช็คว่าผู้เล่นเข้าใจสิ่งที่พูดถึง",
    similar_phrases: ["Is that clear?", "Do you follow me?", "Does that click for you?"],
    match_term: "Does that make sense?",
    match_thai: "เข้าใจไหม?",
  },
  {
    phrase: "I think you're underestimating his range here.",
    thai_meaning: "ผมคิดว่าคุณประเมิน range ของเขาต่ำเกินไปในจุดนี้",
    phrase_type: "challenge",
    phrase_pronunciation: "ไอ ธิงค์ ยัวร์ อันเดอร์เอสติเมทิง ฮิส เรนจ์ เฮียร์",
    word_breakdown: [
      { word: "I",               thai: "ผม",                   pronunciation: "ไอ" },
      { word: "think",           thai: "คิดว่า",               pronunciation: "ธิงค์" },
      { word: "you're",          thai: "คุณกำลัง",             pronunciation: "ยัวร์" },
      { word: "underestimating", thai: "ประเมินต่ำเกินไป",     pronunciation: "อันเดอร์เอสติเมทิง" },
      { word: "his",             thai: "ของเขา",               pronunciation: "ฮิส" },
      { word: "range",           thai: "range",                pronunciation: "เรนจ์" },
      { word: "here",            thai: "ในจุดนี้",              pronunciation: "เฮียร์" },
    ],
    keywords: ["underestimating", "range"],
    situation: "โค้ช challenge ความคิดของผู้เล่นเมื่อเห็นว่าอ่าน range คู่ต่อสู้ผิดพลาด",
    similar_phrases: ["You might be discounting his strong hands here.", "His range is stronger than you think."],
    match_term: "underestimating his range",
    match_thai: "ประเมิน range ต่ำเกินไป",
  },
  {
    phrase: "This is a spot where you can over-bluff.",
    thai_meaning: "นี่คือจุดที่คุณสามารถ bluff ได้มากเกินไป",
    phrase_type: "challenge",
    phrase_pronunciation: "ดิส อิส อะ สปอต แวร์ ยู แคน โอเวอร์บลัฟ",
    word_breakdown: [
      { word: "This",       thai: "นี่",               pronunciation: "ดิส" },
      { word: "is",         thai: "คือ",               pronunciation: "อิส" },
      { word: "a",          thai: "(article)",          pronunciation: "อะ" },
      { word: "spot",       thai: "จุด/สถานการณ์",     pronunciation: "สปอต" },
      { word: "where",      thai: "ที่ซึ่ง",           pronunciation: "แวร์" },
      { word: "you",        thai: "คุณ",               pronunciation: "ยู" },
      { word: "can",        thai: "อาจ",               pronunciation: "แคน" },
      { word: "over-bluff", thai: "bluff มากเกินไป",   pronunciation: "โอเวอร์บลัฟ" },
    ],
    keywords: ["spot", "over-bluff"],
    situation: "โค้ชเตือนว่า spot นี้มีความเสี่ยงที่จะ bluff บ่อยเกิน จนโดน exploit ได้",
    similar_phrases: ["Be careful not to bluff too frequently here.", "Your bluff frequency is too high in this spot."],
    match_term: "spot to over-bluff",
    match_thai: "จุดเสี่ยง bluff เกิน",
  },
  {
    phrase: "Let's think about this from his perspective.",
    thai_meaning: "ลองคิดจากมุมมองของเขาดู",
    phrase_type: "transition",
    phrase_pronunciation: "เลทส์ ธิงค์ อะเบาท์ ดิส ฟรอม ฮิส เพอร์สเปคทิฟ",
    word_breakdown: [
      { word: "Let's",       thai: "มา",              pronunciation: "เลทส์" },
      { word: "think",       thai: "คิด",             pronunciation: "ธิงค์" },
      { word: "about",       thai: "เกี่ยวกับ",       pronunciation: "อะเบาท์" },
      { word: "this",        thai: "สิ่งนี้",         pronunciation: "ดิส" },
      { word: "from",        thai: "จาก",             pronunciation: "ฟรอม" },
      { word: "his",         thai: "ของเขา",          pronunciation: "ฮิส" },
      { word: "perspective", thai: "มุมมอง",          pronunciation: "เพอร์สเปคทิฟ" },
    ],
    keywords: ["perspective"],
    situation: "โค้ชให้ผู้เล่นเปลี่ยนมุมมองมาคิดแทนคู่ต่อสู้ เพื่อเข้าใจ range และ decision ของอีกฝ่าย",
    similar_phrases: ["Put yourself in his shoes.", "How does this look from his side?"],
    match_term: "from his perspective",
    match_thai: "จากมุมมองของเขา",
  },
  {
    phrase: "What hands are you trying to get value from?",
    thai_meaning: "คุณพยายาม get value จากมือไหนบ้าง?",
    phrase_type: "question",
    phrase_pronunciation: "วอท แฮนดส์ อาร์ ยู ไทรอิง ทู เก็ต แวลลิว ฟรอม?",
    word_breakdown: [
      { word: "What",   thai: "มือไหน",             pronunciation: "วอท" },
      { word: "hands",  thai: "มือ (ไพ่)",          pronunciation: "แฮนดส์" },
      { word: "are",    thai: "(กริยาช่วย)",        pronunciation: "อาร์" },
      { word: "you",    thai: "คุณ",               pronunciation: "ยู" },
      { word: "trying", thai: "พยายาม",             pronunciation: "ไทรอิง" },
      { word: "to",     thai: "ที่จะ",             pronunciation: "ทู" },
      { word: "get",    thai: "ได้รับ",            pronunciation: "เก็ต" },
      { word: "value",  thai: "value",             pronunciation: "แวลลิว" },
      { word: "from",   thai: "จาก",               pronunciation: "ฟรอม" },
    ],
    keywords: ["hands", "get value"],
    situation: "โค้ชถามเพื่อให้ระบุว่ามือแบบไหนของคู่ต่อสู้ที่จะ call และทำให้ bet นั้น profitable",
    similar_phrases: ["Which hands are you targeting?", "Who's calling you here and why?"],
    match_term: "get value from?",
    match_thai: "get value จากมือไหน?",
  },
  {
    phrase: "The issue I have with this line is...",
    thai_meaning: "ปัญหาที่ผมมีกับการเล่นแบบนี้คือ...",
    phrase_type: "challenge",
    phrase_pronunciation: "เดอะ อิชชู ไอ แฮฟ วิธ ดิส ไลน์ อิส",
    word_breakdown: [
      { word: "The",   thai: "(article)",           pronunciation: "เดอะ" },
      { word: "issue", thai: "ปัญหา",              pronunciation: "อิชชู" },
      { word: "I",     thai: "ที่ผม",              pronunciation: "ไอ" },
      { word: "have",  thai: "มี",                 pronunciation: "แฮฟ" },
      { word: "with",  thai: "กับ",               pronunciation: "วิธ" },
      { word: "this",  thai: "การเล่น",            pronunciation: "ดิส" },
      { word: "line",  thai: "แนวทางนี้",          pronunciation: "ไลน์" },
      { word: "is",    thai: "คือ",               pronunciation: "อิส" },
    ],
    keywords: ["issue", "line"],
    situation: "โค้ชเริ่มวิจารณ์การเล่นอย่างสุภาพโดยระบุปัญหาเฉพาะจุด ไม่ใช่บอกว่าผิดทั้งหมด",
    similar_phrases: ["The problem with this play is...", "What concerns me about this is..."],
    match_term: "issue with this line",
    match_thai: "ปัญหากับแนวทางนี้",
  },
  {
    phrase: "In theory, you should be mixing here.",
    thai_meaning: "ในทางทฤษฎี คุณควร mix action ในจุดนี้",
    phrase_type: "statement",
    phrase_pronunciation: "อิน ธีโอรี ยู ชูด บี มิกซิง เฮียร์",
    word_breakdown: [
      { word: "In",     thai: "ใน",                pronunciation: "อิน" },
      { word: "theory", thai: "ทางทฤษฎี",          pronunciation: "ธีโอรี" },
      { word: "you",    thai: "คุณ",               pronunciation: "ยู" },
      { word: "should", thai: "ควร",               pronunciation: "ชูด" },
      { word: "be",     thai: "จะ",               pronunciation: "บี" },
      { word: "mixing", thai: "mix action",        pronunciation: "มิกซิง" },
      { word: "here",   thai: "ที่นี่",            pronunciation: "เฮียร์" },
    ],
    keywords: ["theory", "mixing"],
    situation: "โค้ชอ้างถึง GTO concept ว่าควรเล่น mixed strategy แทนที่จะทำ action เดิมทุกครั้ง",
    similar_phrases: ["GTO says you need a mixed strategy here.", "You should not always bet or always check in this spot."],
    match_term: "mixing in theory",
    match_thai: "ในทฤษฎีควร mix",
  },
  {
    phrase: "How does the turn card change things?",
    thai_meaning: "ไพ่ turn ที่ออกมาเปลี่ยนสถานการณ์อย่างไร?",
    phrase_type: "question",
    phrase_pronunciation: "ฮาว ดัซ เดอะ เทิร์น คาร์ด เชนจ์ ธิงส์?",
    word_breakdown: [
      { word: "How",    thai: "อย่างไร",           pronunciation: "ฮาว" },
      { word: "does",   thai: "(กริยาช่วย)",       pronunciation: "ดัซ" },
      { word: "the",    thai: "(article)",          pronunciation: "เดอะ" },
      { word: "turn",   thai: "turn",              pronunciation: "เทิร์น" },
      { word: "card",   thai: "ไพ่",              pronunciation: "คาร์ด" },
      { word: "change", thai: "เปลี่ยน",          pronunciation: "เชนจ์" },
      { word: "things", thai: "สถานการณ์",        pronunciation: "ธิงส์" },
    ],
    keywords: ["turn", "change", "things"],
    situation: "โค้ชถามให้ผู้เล่นวิเคราะห์ว่า turn card กระทบต่อ range advantage และ plan อย่างไร",
    similar_phrases: ["What impact does this card have on ranges?", "How does this runout affect your plan?"],
    match_term: "turn card change things?",
    match_thai: "ไพ่ turn เปลี่ยนอะไรบ้าง?",
  },
  {
    phrase: "You have to balance your checking range here.",
    thai_meaning: "คุณต้อง balance checking range ของคุณในจุดนี้",
    phrase_type: "challenge",
    phrase_pronunciation: "ยู แฮฟ ทู แบลลันซ์ ยัวร์ เช็คอิง เรนจ์ เฮียร์",
    word_breakdown: [
      { word: "You",      thai: "คุณ",               pronunciation: "ยู" },
      { word: "have",     thai: "ต้อง",              pronunciation: "แฮฟ" },
      { word: "to",       thai: "ที่จะ",             pronunciation: "ทู" },
      { word: "balance",  thai: "สมดุล",             pronunciation: "แบลลันซ์" },
      { word: "your",     thai: "ของคุณ",            pronunciation: "ยัวร์" },
      { word: "checking", thai: "checking",          pronunciation: "เช็คอิง" },
      { word: "range",    thai: "range",             pronunciation: "เรนจ์" },
      { word: "here",     thai: "ในจุดนี้",           pronunciation: "เฮียร์" },
    ],
    keywords: ["balance", "checking range"],
    situation: "โค้ชแนะนำให้ผู้เล่นใส่มือดีบางส่วนใน checking range เพื่อไม่ให้ถูก exploit",
    similar_phrases: ["Don't check with only weak hands here.", "You need some strong hands in your check range."],
    match_term: "balance checking range",
    match_thai: "ต้อง balance checking range",
  },
  {
    phrase: "What's the worst thing that can happen?",
    thai_meaning: "อะไรคือสิ่งที่แย่ที่สุดที่จะเกิดขึ้น?",
    phrase_type: "question",
    phrase_pronunciation: "วอทส์ เดอะ เวิร์สท์ ธิง แดท แคน แฮปเพน?",
    word_breakdown: [
      { word: "What's", thai: "อะไรคือ",            pronunciation: "วอทส์" },
      { word: "the",    thai: "(article)",           pronunciation: "เดอะ" },
      { word: "worst",  thai: "แย่ที่สุด",          pronunciation: "เวิร์สท์" },
      { word: "thing",  thai: "สิ่งที่",            pronunciation: "ธิง" },
      { word: "that",   thai: "ที่",               pronunciation: "แดท" },
      { word: "can",    thai: "อาจ",               pronunciation: "แคน" },
      { word: "happen", thai: "เกิดขึ้น",           pronunciation: "แฮปเพน" },
    ],
    keywords: ["worst", "happen"],
    situation: "โค้ชถามให้ผู้เล่นคิดถึง downside ของ action นั้น เพื่อประเมินความเสี่ยงอย่างครบถ้วน",
    similar_phrases: ["What's your downside here?", "Think about the worst case scenario."],
    match_term: "worst thing that can happen?",
    match_thai: "สิ่งที่แย่ที่สุดคืออะไร?",
  },
  {
    phrase: "That's a valid point, but consider this...",
    thai_meaning: "นั่นเป็นประเด็นที่ถูกต้อง แต่ลองพิจารณาสิ่งนี้ด้วย...",
    phrase_type: "transition",
    phrase_pronunciation: "แดทส์ อะ แวลลิด พอยท์ บัท คอนซิเดอร์ ดิส",
    word_breakdown: [
      { word: "That's",   thai: "นั่น",             pronunciation: "แดทส์" },
      { word: "a",        thai: "เป็น",             pronunciation: "อะ" },
      { word: "valid",    thai: "ถูกต้อง",          pronunciation: "แวลลิด" },
      { word: "point",    thai: "ประเด็น",          pronunciation: "พอยท์" },
      { word: "but",      thai: "แต่",              pronunciation: "บัท" },
      { word: "consider", thai: "ลองพิจารณา",       pronunciation: "คอนซิเดอร์" },
      { word: "this",     thai: "สิ่งนี้",          pronunciation: "ดิส" },
    ],
    keywords: ["valid", "consider"],
    situation: "โค้ชยอมรับความคิดของผู้เล่นบางส่วน แต่เพิ่มมุมมองที่ผู้เล่นอาจมองข้ามไป",
    similar_phrases: ["Good point, however...", "You're right, but think about this..."],
    match_term: "valid point, but consider...",
    match_thai: "ถูกต้องแต่ลองพิจารณาสิ่งนี้",
  },
  {
    phrase: "You're putting him in a really tough spot.",
    thai_meaning: "คุณกำลังทำให้เขาอยู่ในสถานการณ์ที่ยากมาก",
    phrase_type: "statement",
    phrase_pronunciation: "ยัวร์ พุตทิง ฮิม อิน อะ รีลลี ทัฟ สปอต",
    word_breakdown: [
      { word: "You're",  thai: "คุณกำลัง",          pronunciation: "ยัวร์" },
      { word: "putting", thai: "ทำให้",             pronunciation: "พุตทิง" },
      { word: "him",     thai: "เขา",              pronunciation: "ฮิม" },
      { word: "in",      thai: "อยู่ใน",           pronunciation: "อิน" },
      { word: "a",       thai: "(article)",         pronunciation: "อะ" },
      { word: "really",  thai: "จริงๆ",            pronunciation: "รีลลี" },
      { word: "tough",   thai: "ยาก",              pronunciation: "ทัฟ" },
      { word: "spot",    thai: "สถานการณ์",        pronunciation: "สปอต" },
    ],
    keywords: ["tough", "spot"],
    situation: "โค้ชชมเมื่อผู้เล่นสร้าง pressure ที่ดีจนคู่ต่อสู้ต้องตัดสินใจในสถานการณ์ยาก",
    similar_phrases: ["You're making this really difficult for him.", "He has a tough decision here because of you."],
    match_term: "tough spot for him",
    match_thai: "ทำให้เขาอยู่ใน spot ยาก",
  },
  {
    phrase: "Let's run through the range breakdown together.",
    thai_meaning: "มา breakdown range กันทีละส่วน",
    phrase_type: "transition",
    phrase_pronunciation: "เลทส์ รัน ทรู เดอะ เรนจ์ เบรคดาวน์ ทูเก็ธเธอร์",
    word_breakdown: [
      { word: "Let's",     thai: "มา",              pronunciation: "เลทส์" },
      { word: "run",       thai: "วิ่งผ่าน/ไล่",   pronunciation: "รัน" },
      { word: "through",   thai: "ผ่าน",            pronunciation: "ทรู" },
      { word: "the",       thai: "(article)",        pronunciation: "เดอะ" },
      { word: "range",     thai: "range",           pronunciation: "เรนจ์" },
      { word: "breakdown", thai: "การแบ่งส่วน",     pronunciation: "เบรคดาวน์" },
      { word: "together",  thai: "ด้วยกัน",         pronunciation: "ทูเก็ธเธอร์" },
    ],
    keywords: ["run through", "range breakdown"],
    situation: "โค้ชเสนอให้วิเคราะห์ range ของคู่ต่อสู้อย่างเป็นระบบ ทีละหมวดหมู่ของมือ",
    similar_phrases: ["Let's categorize his range here.", "Let's map out what hands he can have."],
    match_term: "range breakdown",
    match_thai: "ไล่ breakdown range ด้วยกัน",
  },
];
